import type { Chemical } from "./types"
import { GENERATED_COMPOUNDS } from "./compounds-generated"

const m = (value: number): { value: number; source: "measured" } => ({ value, source: "measured" })
const e = (value: number): { value: number; source: "estimated" } => ({ value, source: "estimated" })
const u = (): { value: null; source: "unknown" } => ({ value: null, source: "unknown" })

// The CID-generated set (scripts/cids.json → scripts/generate-compounds.ts) is
// merged below. A curated record with the same PubChem CID wins the slot: it
// carries measured NIST physics (Antoine coeffs, vapor pressures) and richer
// aliases, so a generated estimate never overwrites a measured value.
const CURATED_COMPOUNDS: Chemical[] = [
  {
    id: "ethanol",
    name: "Ethanol",
    synonyms: ["ethyl alcohol", "alcohol", "grain alcohol", "drinking alcohol"],
    cas: "64-17-5",
    smiles: "CCO",
    props: {
      molecularWeight: m(46.07),
      boilingPoint: m(78.37),
      vaporPressure25: m(7870),
      antoine: { a: 8.20417, b: 1642.89, c: 230.3 },
      functionalGroups: ["alcohol"],
      redoxActive: true,
      odorDescriptor: "alcoholic, solvent",
    },
    sourceRefs: ["PubChem CID 702", "NIST Webbook"],
  },
  {
    id: "methanol",
    name: "Methanol",
    synonyms: ["methyl alcohol", "wood alcohol"],
    cas: "67-56-1",
    smiles: "CO",
    props: {
      molecularWeight: m(32.04),
      boilingPoint: m(64.7),
      vaporPressure25: m(16900),
      antoine: { a: 8.08097, b: 1582.271, c: 239.726 },
      functionalGroups: ["alcohol"],
      redoxActive: true,
      odorDescriptor: "alcoholic, pungent",
    },
    sourceRefs: ["PubChem CID 887", "NIST Webbook"],
  },
  {
    id: "isopropanol",
    name: "Isopropanol",
    synonyms: ["isopropyl alcohol", "rubbing alcohol", "propan-2-ol", "IPA"],
    cas: "67-63-0",
    smiles: "CC(C)O",
    props: {
      molecularWeight: m(60.1),
      boilingPoint: m(82.6),
      vaporPressure25: m(6020),
      antoine: { a: 8.87829, b: 2010.33, c: 252.636 },
      functionalGroups: ["alcohol"],
      redoxActive: true,
      odorDescriptor: "alcoholic, sweet",
    },
    sourceRefs: ["PubChem CID 3776", "NIST Webbook"],
  },
  {
    id: "acetone",
    name: "Acetone",
    synonyms: ["propanone", "dimethyl ketone", "nail polish remover"],
    cas: "67-64-1",
    smiles: "CC(=O)C",
    props: {
      molecularWeight: m(58.08),
      boilingPoint: m(56.05),
      vaporPressure25: m(30600),
      antoine: { a: 7.11714, b: 1210.595, c: 229.664 },
      functionalGroups: ["ketone"],
      redoxActive: true,
      odorDescriptor: "sweet, fruity, solvent",
    },
    sourceRefs: ["PubChem CID 180", "NIST Webbook"],
  },
  {
    id: "acetaldehyde",
    name: "Acetaldehyde",
    synonyms: ["ethanal", "acetaldehyde (in foods)"],
    cas: "75-07-0",
    smiles: "CC=O",
    props: {
      molecularWeight: m(44.05),
      boilingPoint: m(20.2),
      vaporPressure25: m(120000),
      functionalGroups: ["aldehyde"],
      redoxActive: true,
      odorDescriptor: "pungent, fruity",
    },
    sourceRefs: ["PubChem CID 177", "NIST Webbook"],
  },
  {
    id: "acetic-acid",
    name: "Acetic acid",
    synonyms: ["ethanoic acid", "vinegar", "glacial acetic acid"],
    cas: "64-19-7",
    smiles: "CC(=O)O",
    props: {
      molecularWeight: m(60.05),
      boilingPoint: m(118),
      vaporPressure25: m(2090),
      functionalGroups: ["carboxylic acid"],
      redoxActive: true,
      odorDescriptor: "vinegar, sour",
    },
    sourceRefs: ["PubChem CID 176", "NIST Webbook"],
  },
  {
    id: "butyric-acid",
    name: "Butyric acid",
    synonyms: ["butanoic acid", "n-butyric acid"],
    cas: "107-92-6",
    smiles: "CCCC(=O)O",
    props: {
      molecularWeight: m(88.11),
      boilingPoint: m(163.5),
      vaporPressure25: e(110),
      functionalGroups: ["carboxylic acid"],
      redoxActive: true,
      odorDescriptor: "rancid butter, vomit",
    },
    sourceRefs: ["PubChem CID 264", "NIST Webbook"],
  },
  {
    id: "benzene",
    name: "Benzene",
    synonyms: ["benzin"],
    cas: "71-43-2",
    smiles: "c1ccccc1",
    props: {
      molecularWeight: m(78.11),
      boilingPoint: m(80.1),
      vaporPressure25: m(12700),
      antoine: { a: 6.90565, b: 1211.033, c: 220.79 },
      functionalGroups: ["aromatic"],
      redoxActive: true,
      odorDescriptor: "aromatic, solvent",
    },
    sourceRefs: ["PubChem CID 241", "NIST Webbook"],
  },
  {
    id: "toluene",
    name: "Toluene",
    synonyms: ["methylbenzene", "toluol"],
    cas: "108-88-3",
    smiles: "Cc1ccccc1",
    props: {
      molecularWeight: m(92.14),
      boilingPoint: m(110.6),
      vaporPressure25: m(3790),
      antoine: { a: 6.95464, b: 1344.8, c: 219.48 },
      functionalGroups: ["aromatic"],
      redoxActive: true,
      odorDescriptor: "aromatic, paint-like",
    },
    sourceRefs: ["PubChem CID 1140", "NIST Webbook"],
  },
  {
    id: "xylene",
    name: "Xylene",
    synonyms: ["dimethylbenzene", "m-xylene", "xylol"],
    cas: "108-38-3",
    smiles: "Cc1cccc(C)c1",
    props: {
      molecularWeight: m(106.17),
      boilingPoint: m(139),
      vaporPressure25: e(1100),
      functionalGroups: ["aromatic"],
      redoxActive: true,
      odorDescriptor: "sweet, solvent",
    },
    sourceRefs: ["PubChem CID 7809", "NIST Webbook"],
  },
  {
    id: "hexane",
    name: "n-Hexane",
    synonyms: ["hexane", "normal hexane"],
    cas: "110-54-3",
    smiles: "CCCCCC",
    props: {
      molecularWeight: m(86.18),
      boilingPoint: m(68.7),
      vaporPressure25: m(20000),
      functionalGroups: ["alkane"],
      redoxActive: true,
      odorDescriptor: "gasoline-like, faint",
    },
    sourceRefs: ["PubChem CID 8100", "NIST Webbook"],
  },
  {
    id: "hexene",
    name: "1-Hexene",
    synonyms: ["hexene", "hex-1-ene"],
    cas: "592-41-6",
    smiles: "CCCCC=C",
    pubchemCid: 11597,
    props: {
      molecularWeight: m(84.16),
      boilingPoint: m(63.5),
      vaporPressure25: e(24700),
      functionalGroups: ["alkene"],
      redoxActive: true,
      odorDescriptor: "gasoline-like, faint",
    },
    sourceRefs: ["PubChem CID 11597", "NIST Webbook"],
  },
  {
    id: "isopentane",
    name: "Isopentane",
    synonyms: ["2-methylbutane"],
    cas: "78-78-4",
    smiles: "CCC(C)C",
    props: {
      molecularWeight: m(72.15),
      boilingPoint: m(27.8),
      vaporPressure25: e(95000),
      functionalGroups: ["alkane"],
      redoxActive: true,
      odorDescriptor: "gasoline-like",
    },
    sourceRefs: ["PubChem CID 6556", "NIST Webbook"],
  },
  {
    id: "isoamyl-acetate",
    name: "Isoamyl acetate",
    synonyms: ["isopentyl acetate", "3-methylbutyl acetate", "banana oil"],
    cas: "123-92-2",
    smiles: "CC(C)CCOC(C)=O",
    props: {
      molecularWeight: m(130.18),
      boilingPoint: m(142),
      vaporPressure25: e(700),
      functionalGroups: ["ester"],
      redoxActive: true,
      odorDescriptor: "banana, pear",
    },
    sourceRefs: ["PubChem CID 31276", "NIST Webbook"],
  },
  {
    id: "ethyl-acetate",
    name: "Ethyl acetate",
    synonyms: ["acetic ester", "ethyl ethanoate"],
    cas: "141-78-6",
    smiles: "CCOC(C)=O",
    props: {
      molecularWeight: m(88.11),
      boilingPoint: m(77.1),
      vaporPressure25: m(12600),
      functionalGroups: ["ester"],
      redoxActive: true,
      odorDescriptor: "sweet, fruity, solvent",
    },
    sourceRefs: ["PubChem CID 8857", "NIST Webbook"],
  },
  {
    id: "methyl-acetate",
    name: "Methyl acetate",
    synonyms: ["methyl ethanoate", "acetic acid methyl ester"],
    cas: "79-20-9",
    smiles: "CC(=O)OC",
    pubchemCid: 6584,
    props: {
      molecularWeight: m(74.08),
      boilingPoint: m(57.8),
      vaporPressure25: e(24900),
      functionalGroups: ["ester"],
      redoxActive: true,
      odorDescriptor: "sweet, fruity, solvent",
    },
    sourceRefs: ["PubChem CID 6584", "NIST Webbook"],
  },
  {
    id: "butyl-acetate",
    name: "Butyl acetate",
    synonyms: ["n-butyl acetate", "butyl ethanoate"],
    cas: "123-86-4",
    smiles: "CCCCOC(C)=O",
    props: {
      molecularWeight: m(116.16),
      boilingPoint: m(126),
      vaporPressure25: e(1330),
      functionalGroups: ["ester"],
      redoxActive: true,
      odorDescriptor: "sweet, fruity, banana",
    },
    sourceRefs: ["PubChem CID 31272", "NIST Webbook"],
  },
  {
    id: "isoamyl-butyrate",
    name: "Isoamyl butyrate",
    synonyms: ["isopentyl butyrate", "3-methylbutyl butanoate"],
    cas: "106-27-4",
    smiles: "CCCC(=O)OCCC(C)C",
    props: {
      molecularWeight: m(158.24),
      boilingPoint: e(179),
      vaporPressure25: e(60),
      functionalGroups: ["ester"],
      redoxActive: true,
      odorDescriptor: "fruity, apricot",
    },
    sourceRefs: ["PubChem CID 7794"],
  },
  {
    id: "isoamyl-isovalerate",
    name: "Isoamyl isovalerate",
    synonyms: ["isopentyl 3-methylbutanoate", "isopentyl isovalerate"],
    cas: "659-70-1",
    smiles: "CC(C)CC(=O)OCCC(C)C",
    props: {
      molecularWeight: m(172.26),
      boilingPoint: e(193),
      vaporPressure25: e(40),
      functionalGroups: ["ester"],
      redoxActive: true,
      odorDescriptor: "apple, fruity",
    },
    sourceRefs: ["PubChem CID 69021"],
  },
  {
    id: "methyl-butyrate",
    name: "Methyl butyrate",
    synonyms: ["methyl butanoate"],
    cas: "623-42-7",
    smiles: "CCCC(=O)OC",
    props: {
      molecularWeight: m(102.13),
      boilingPoint: m(102.8),
      vaporPressure25: e(3000),
      functionalGroups: ["ester"],
      redoxActive: true,
      odorDescriptor: "apple, pineapple",
    },
    sourceRefs: ["PubChem CID 12180"],
  },
  {
    id: "ethyl-butyrate",
    name: "Ethyl butyrate",
    synonyms: ["ethyl butanoate"],
    cas: "105-54-4",
    smiles: "CCCC(=O)OCC",
    props: {
      molecularWeight: m(116.16),
      boilingPoint: m(121.5),
      vaporPressure25: e(2000),
      functionalGroups: ["ester"],
      redoxActive: true,
      odorDescriptor: "fruity, pineapple",
    },
    sourceRefs: ["PubChem CID 7762"],
  },
  {
    id: "hexanal",
    name: "Hexanal",
    synonyms: ["n-hexanal", "caproaldehyde", "hexyl aldehyde"],
    cas: "66-25-1",
    smiles: "CCCCCC=O",
    props: {
      molecularWeight: m(100.16),
      boilingPoint: m(131),
      vaporPressure25: e(1330),
      functionalGroups: ["aldehyde"],
      redoxActive: true,
      odorDescriptor: "grassy, green, tallow",
    },
    sourceRefs: ["PubChem CID 6184"],
  },
  {
    id: "e2-hexenal",
    name: "(E)-2-Hexenal",
    synonyms: ["trans-2-hexenal", "leaf aldehyde", "hex-2-enal"],
    cas: "6728-26-3",
    smiles: "CCCC=CC=O",
    props: {
      molecularWeight: m(98.14),
      boilingPoint: m(147),
      vaporPressure25: e(600),
      functionalGroups: ["aldehyde", "alkene"],
      redoxActive: true,
      odorDescriptor: "green leaf, apple",
    },
    sourceRefs: ["PubChem CID 5281168"],
  },
  {
    id: "hexanol",
    name: "1-Hexanol",
    synonyms: ["n-hexanol", "hexan-1-ol"],
    cas: "111-27-3",
    smiles: "CCCCCCO",
    props: {
      molecularWeight: m(102.17),
      boilingPoint: m(157),
      vaporPressure25: e(133),
      functionalGroups: ["alcohol"],
      redoxActive: true,
      odorDescriptor: "green, grassy, fruity",
    },
    sourceRefs: ["PubChem CID 8103"],
  },
  {
    id: "eugenol",
    name: "Eugenol",
    synonyms: ["clove oil", "4-allyl-2-methoxyphenol"],
    cas: "97-53-0",
    smiles: "COc1cc(CC=C)ccc1O",
    props: {
      molecularWeight: m(164.2),
      boilingPoint: m(254),
      vaporPressure25: e(2.7),
      functionalGroups: ["phenol", "ether", "alkene"],
      redoxActive: true,
      odorDescriptor: "clove, spicy",
    },
    sourceRefs: ["PubChem CID 3314"],
  },
  {
    id: "cinnamaldehyde",
    name: "Cinnamaldehyde",
    synonyms: ["cinnamic aldehyde", "3-phenylpropenal", "cinnamon aldehyde"],
    cas: "104-55-2",
    smiles: "O=C/C=C/c1ccccc1",
    props: {
      molecularWeight: m(132.16),
      boilingPoint: m(248),
      vaporPressure25: e(1.3),
      functionalGroups: ["aldehyde", "alkene", "aromatic"],
      redoxActive: true,
      odorDescriptor: "cinnamon, spicy",
    },
    sourceRefs: ["PubChem CID 637511"],
  },
  {
    id: "linalool",
    name: "Linalool",
    synonyms: ["linalol", "coriandrol"],
    cas: "78-70-6",
    smiles: "CC(C)=CCCC(C)(O)C=C",
    props: {
      molecularWeight: m(154.25),
      boilingPoint: m(198),
      vaporPressure25: e(26),
      functionalGroups: ["alcohol", "terpene", "alkene"],
      redoxActive: true,
      odorDescriptor: "floral, lavender, citrus",
    },
    sourceRefs: ["PubChem CID 6549"],
  },
  {
    id: "limonene",
    name: "Limonene",
    synonyms: ["d-limonene", "citrus terpene"],
    cas: "5989-27-5",
    smiles: "CC1=CCC(CC1)C(C)=C",
    props: {
      molecularWeight: m(136.23),
      boilingPoint: m(176),
      vaporPressure25: e(270),
      functionalGroups: ["terpene", "alkene"],
      redoxActive: true,
      odorDescriptor: "citrus, orange",
    },
    sourceRefs: ["PubChem CID 440917"],
  },
  {
    id: "alpha-pinene",
    name: "alpha-Pinene",
    synonyms: ["alpha-pinene", "pinene"],
    cas: "80-56-8",
    smiles: "CC1=CCC2CC1C2(C)C",
    props: {
      molecularWeight: m(136.23),
      boilingPoint: m(155),
      vaporPressure25: e(627),
      functionalGroups: ["terpene", "alkene"],
      redoxActive: true,
      odorDescriptor: "pine, resinous",
    },
    sourceRefs: ["PubChem CID 6654"],
  },
  {
    id: "myrcene",
    name: "beta-Myrcene",
    synonyms: ["myrcene", "beta-myrcene"],
    cas: "123-35-3",
    smiles: "CC(=C)CCC=C(C)C",
    props: {
      molecularWeight: m(136.23),
      boilingPoint: e(167),
      vaporPressure25: e(300),
      functionalGroups: ["terpene", "alkene"],
      redoxActive: true,
      odorDescriptor: "resinous, balsamic",
    },
    sourceRefs: ["PubChem CID 31253"],
  },
  {
    id: "menthol",
    name: "Menthol",
    synonyms: ["l-menthol", "peppermint camphor"],
    cas: "2216-51-5",
    smiles: "CC1CCC(C(C1)O)C(C)C",
    props: {
      molecularWeight: m(156.27),
      boilingPoint: m(212),
      vaporPressure25: e(7),
      functionalGroups: ["alcohol", "terpene"],
      redoxActive: true,
      odorDescriptor: "mint, cooling",
    },
    sourceRefs: ["PubChem CID 165675"],
  },
  {
    id: "menthone",
    name: "Menthone",
    synonyms: ["l-menthone", "peppermint ketone"],
    cas: "10458-14-7",
    smiles: "CC1CCC(C(=O)C1)C(C)C",
    props: {
      molecularWeight: m(154.25),
      boilingPoint: e(207),
      vaporPressure25: e(26),
      functionalGroups: ["ketone", "terpene"],
      redoxActive: true,
      odorDescriptor: "mint, peppermint",
    },
    sourceRefs: ["PubChem CID 165834"],
  },
  {
    id: "guaiacol",
    name: "Guaiacol",
    synonyms: ["2-methoxyphenol", "o-methoxyphenol"],
    cas: "90-05-1",
    smiles: "COc1ccccc1O",
    props: {
      molecularWeight: m(124.14),
      boilingPoint: m(205),
      vaporPressure25: e(20),
      functionalGroups: ["phenol", "ether"],
      redoxActive: true,
      odorDescriptor: "smoky, medicinal",
    },
    sourceRefs: ["PubChem CID 460"],
  },
  {
    id: "phenol",
    name: "Phenol",
    synonyms: ["carbolic acid", "hydroxybenzene"],
    cas: "108-95-2",
    smiles: "Oc1ccccc1",
    props: {
      molecularWeight: m(94.11),
      boilingPoint: m(181.8),
      vaporPressure25: e(47),
      functionalGroups: ["phenol", "aromatic"],
      redoxActive: true,
      odorDescriptor: "phenolic, tar-like",
    },
    sourceRefs: ["PubChem CID 996"],
  },
  {
    id: "furfural",
    name: "Furfural",
    synonyms: ["furfuraldehyde", "2-furaldehyde"],
    cas: "98-01-1",
    smiles: "O=Cc1ccco1",
    props: {
      molecularWeight: m(96.08),
      boilingPoint: m(161.7),
      vaporPressure25: e(260),
      functionalGroups: ["aldehyde", "furan", "aromatic"],
      redoxActive: true,
      odorDescriptor: "almond, bready, caramel",
    },
    sourceRefs: ["PubChem CID 7362"],
  },
  {
    id: "diacetyl",
    name: "2,3-Butanedione",
    synonyms: ["diacetyl", "dimethyl diketone"],
    cas: "431-03-8",
    smiles: "CC(=O)C(C)=O",
    props: {
      molecularWeight: m(86.09),
      boilingPoint: m(88),
      vaporPressure25: e(7000),
      functionalGroups: ["ketone", "diketone"],
      redoxActive: true,
      odorDescriptor: "buttery, creamy",
    },
    sourceRefs: ["PubChem CID 650"],
  },
  {
    id: "diallyl-disulfide",
    name: "Diallyl disulfide",
    synonyms: ["garlic oil", "4,5-dithia-1,7-octadiene"],
    cas: "2179-57-9",
    smiles: "C=CCSSCC=C",
    props: {
      molecularWeight: m(146.27),
      boilingPoint: e(177),
      vaporPressure25: e(130),
      functionalGroups: ["thioether", "sulfur", "alkene"],
      redoxActive: true,
      odorDescriptor: "garlic, pungent",
    },
    sourceRefs: ["PubChem CID 16590"],
  },
  {
    id: "ammonia",
    name: "Ammonia",
    synonyms: ["NH3", "ammonium gas"],
    cas: "7664-41-7",
    smiles: "N",
    props: {
      molecularWeight: m(17.03),
      boilingPoint: m(-33.3),
      vaporPressure25: u(),
      gas: true,
      functionalGroups: ["amine"],
      redoxActive: true,
      odorDescriptor: "pungent, sharp",
    },
    sourceRefs: ["PubChem CID 222"],
  },
  {
    id: "methane",
    name: "Methane",
    synonyms: ["natural gas", "CH4"],
    cas: "74-82-8",
    smiles: "C",
    props: {
      molecularWeight: m(16.04),
      boilingPoint: m(-161.5),
      vaporPressure25: u(),
      gas: true,
      functionalGroups: ["alkane"],
      redoxActive: true,
      odorDescriptor: "odorless (odorized in supply)",
    },
    sourceRefs: ["PubChem CID 297"],
  },
  {
    id: "propane",
    name: "Propane",
    synonyms: ["LPG", "liquefied petroleum gas"],
    cas: "74-98-6",
    smiles: "CCC",
    props: {
      molecularWeight: m(44.1),
      boilingPoint: m(-42.1),
      vaporPressure25: u(),
      gas: true,
      functionalGroups: ["alkane"],
      redoxActive: true,
      odorDescriptor: "odorless (odorized)",
    },
    sourceRefs: ["PubChem CID 6334"],
  },
  {
    id: "butane",
    name: "n-Butane",
    synonyms: ["butane", "liquefied gas"],
    cas: "106-97-8",
    smiles: "CCCC",
    props: {
      molecularWeight: m(58.12),
      boilingPoint: m(-0.5),
      vaporPressure25: e(240000),
      gas: true,
      functionalGroups: ["alkane"],
      redoxActive: true,
      odorDescriptor: "odorless (odorized)",
    },
    sourceRefs: ["PubChem CID 7843"],
  },
  {
    id: "hydrogen-sulfide",
    name: "Hydrogen sulfide",
    synonyms: ["H2S", "sulfane", "sewer gas"],
    cas: "7783-06-4",
    smiles: "S",
    props: {
      molecularWeight: m(34.08),
      boilingPoint: m(-60.3),
      vaporPressure25: u(),
      gas: true,
      functionalGroups: ["thiol", "sulfur"],
      redoxActive: true,
      odorDescriptor: "rotten eggs",
    },
    sourceRefs: ["PubChem CID 402"],
  },
  {
    id: "methanethiol",
    name: "Methanethiol",
    synonyms: ["methyl mercaptan", "mercaptomethane"],
    cas: "74-93-1",
    smiles: "CS",
    props: {
      molecularWeight: m(48.11),
      boilingPoint: m(5.95),
      vaporPressure25: u(),
      gas: true,
      functionalGroups: ["thiol", "sulfur"],
      redoxActive: true,
      odorDescriptor: "rotten cabbage, sulfurous",
    },
    sourceRefs: ["PubChem CID 855"],
  },
  {
    id: "ethanethiol",
    name: "Ethanethiol",
    synonyms: ["ethyl mercaptan", "mercaptoethane"],
    cas: "75-08-1",
    smiles: "CCS",
    pubchemCid: 6343,
    props: {
      molecularWeight: m(62.14),
      boilingPoint: m(35.1),
      vaporPressure25: e(70794),
      functionalGroups: ["thiol", "sulfur"],
      redoxActive: true,
      odorDescriptor: "fruity, sulfurous",
    },
    sourceRefs: ["PubChem CID 6343", "NIST Webbook"],
  },
  {
    id: "dimethyl-sulfide",
    name: "Dimethyl sulfide",
    synonyms: ["DMS", "methylthiomethane"],
    cas: "75-18-3",
    smiles: "CSC",
    props: {
      molecularWeight: m(62.13),
      boilingPoint: m(37.3),
      vaporPressure25: e(64000),
      functionalGroups: ["thioether", "sulfur"],
      redoxActive: true,
      odorDescriptor: "seafood, cabbage, sulfurous",
    },
    sourceRefs: ["PubChem CID 1068"],
  },
  {
    id: "ethylene",
    name: "Ethylene",
    synonyms: ["ethene", "fruit ripening gas"],
    cas: "74-85-1",
    smiles: "C=C",
    props: {
      molecularWeight: m(28.05),
      boilingPoint: m(-103.7),
      vaporPressure25: u(),
      gas: true,
      functionalGroups: ["alkene"],
      redoxActive: true,
      odorDescriptor: "sweet, ethereal",
    },
    sourceRefs: ["PubChem CID 6325"],
  },
  {
    id: "carbon-monoxide",
    name: "Carbon monoxide",
    synonyms: ["CO", "exhaust gas"],
    cas: "630-08-0",
    smiles: "[C-]#[O+]",
    props: {
      molecularWeight: m(28.01),
      boilingPoint: m(-191.5),
      vaporPressure25: u(),
      gas: true,
      functionalGroups: ["inorganic"],
      redoxActive: true,
      odorDescriptor: "odorless",
    },
    sourceRefs: ["PubChem CID 281"],
  },
  {
    id: "carbon-dioxide",
    name: "Carbon dioxide",
    synonyms: ["CO2", "carbonic anhydride"],
    cas: "124-38-9",
    smiles: "O=C=O",
    props: {
      molecularWeight: m(44.01),
      boilingPoint: m(-78.5),
      vaporPressure25: u(),
      gas: true,
      functionalGroups: ["inorganic"],
      redoxActive: false,
      nonRedox: true,
      odorDescriptor: "odorless",
    },
    sourceRefs: ["PubChem CID 280"],
  },
  {
    id: "nitrogen",
    name: "Nitrogen",
    synonyms: ["N2", "dinitrogen"],
    cas: "7727-37-9",
    smiles: "N#N",
    props: {
      molecularWeight: m(28.01),
      boilingPoint: m(-195.8),
      vaporPressure25: u(),
      gas: true,
      functionalGroups: ["inorganic"],
      redoxActive: false,
      nonRedox: true,
      odorDescriptor: "odorless",
    },
    sourceRefs: ["PubChem CID 947"],
  },
  {
    id: "oxygen",
    name: "Oxygen",
    synonyms: ["O2", "dioxygen"],
    cas: "7782-44-7",
    smiles: "O=O",
    props: {
      molecularWeight: m(32.0),
      boilingPoint: m(-183),
      vaporPressure25: u(),
      gas: true,
      functionalGroups: ["inorganic"],
      redoxActive: false,
      nonRedox: false,
      odorDescriptor: "odorless",
    },
    sourceRefs: ["PubChem CID 977"],
  },
  {
    id: "water",
    name: "Water",
    synonyms: ["H2O", "water vapor", "humidity"],
    cas: "7732-18-5",
    smiles: "O",
    props: {
      molecularWeight: m(18.02),
      boilingPoint: m(100),
      vaporPressure25: m(3170),
      functionalGroups: ["inorganic"],
      redoxActive: false,
      nonRedox: false,
      odorDescriptor: "odorless (humidity response)",
    },
    sourceRefs: ["PubChem CID 962"],
  },
]

const curatedCids = new Set<number>()
for (const c of CURATED_COMPOUNDS) {
  if (c.pubchemCid != null) curatedCids.add(c.pubchemCid)
}
const GENERATED = GENERATED_COMPOUNDS.filter((c) => c.pubchemCid == null || !curatedCids.has(c.pubchemCid))

export const COMPOUNDS: Chemical[] = [...CURATED_COMPOUNDS, ...GENERATED]
export const COMPOUND_BY_ID: Map<string, Chemical> = new Map(COMPOUNDS.map((c) => [c.id, c]))
export const REFERENCE_COMPOUND = COMPOUND_BY_ID.get("ethanol")

if (!REFERENCE_COMPOUND) {
  throw new Error("Reference compound 'ethanol' missing from bundled dataset")
}
