import type { Composite } from "./types"

const w = (value: number, source: "measured" | "estimated" = "estimated") => ({
  weightFraction: { value, source },
  chemicalId: "",
})

export const COMPOSITES: Composite[] = [
  {
    id: "banana",
    name: "Banana",
    kind: "food",
    synonyms: ["ripe banana", "banana fruit", "banana aroma"],
    constituents: [
      { ...w(0.5), chemicalId: "isoamyl-acetate" },
      { ...w(0.15), chemicalId: "isoamyl-butyrate" },
      { ...w(0.1), chemicalId: "butyl-acetate" },
      { ...w(0.1), chemicalId: "isoamyl-isovalerate" },
      { ...w(0.05), chemicalId: "hexanal" },
      { ...w(0.05), chemicalId: "e2-hexenal" },
      { ...w(0.05), chemicalId: "hexanol" },
    ],
    notes:
      "Character impact is isoamyl acetate; esters dominate ripe-fruit headspace. Profile varies with ripeness (green stage is aldehyde-heavy).",
    sourceRefs: ["Zhu et al. 2018 (Molecules)", "Pino & Febles 2013", "Sutikdja et al. 2012"],
  },
  {
    id: "cinnamon",
    name: "Cinnamon",
    kind: "spice",
    synonyms: ["cinnamon bark", "cinnamon powder", "ceylon cinnamon"],
    constituents: [
      { ...w(0.65), chemicalId: "cinnamaldehyde" },
      { ...w(0.2), chemicalId: "eugenol" },
      { ...w(0.05), chemicalId: "linalool" },
      { ...w(0.05), chemicalId: "limonene" },
    ],
    notes: "Simplified profile dominated by cinnamaldehyde (bark).",
    sourceRefs: ["PubChem", "FlavorDB ingredient profiles"],
  },
  {
    id: "coffee",
    name: "Coffee",
    kind: "beverage",
    synonyms: ["roasted coffee", "coffee beans", "espresso"],
    constituents: [
      { ...w(0.25), chemicalId: "diacetyl" },
      { ...w(0.2), chemicalId: "furfural" },
      { ...w(0.15), chemicalId: "acetaldehyde" },
      { ...w(0.15), chemicalId: "acetic-acid" },
      { ...w(0.1), chemicalId: "guaiacol" },
    ],
    notes:
      "Highly complex headspace (200+ VOCs); this is a simplified representative subset of potent roast volatiles.",
    sourceRefs: ["FlavorDB2", "Chambers & Koppel 2013 (Molecules)"],
  },
  {
    id: "garlic",
    name: "Garlic",
    kind: "food",
    synonyms: ["raw garlic", "garlic clove", "garlic powder"],
    constituents: [
      { ...w(0.6), chemicalId: "diallyl-disulfide" },
      { ...w(0.15), chemicalId: "methanethiol" },
      { ...w(0.1), chemicalId: "dimethyl-sulfide" },
    ],
    notes: "Organosulfur compounds dominate and are potent MOX-reducing agents.",
    sourceRefs: ["FlavorDB ingredient profiles", "Lanzotti 2006"],
  },
  {
    id: "peppermint",
    name: "Peppermint",
    kind: "spice",
    synonyms: ["mint", "spearmint", "peppermint oil"],
    constituents: [
      { ...w(0.55), chemicalId: "menthol" },
      { ...w(0.3), chemicalId: "menthone" },
      { ...w(0.15), chemicalId: "limonene" },
    ],
    notes: "Menthol + menthone dominate; limonene adds citrus lift.",
    sourceRefs: ["FlavorDB ingredient profiles"],
  },
  {
    id: "lemon",
    name: "Lemon",
    kind: "food",
    synonyms: ["lemon peel", "lemon zest", "citrus lemon"],
    constituents: [
      { ...w(0.6), chemicalId: "limonene" },
      { ...w(0.15), chemicalId: "linalool" },
      { ...w(0.1), chemicalId: "alpha-pinene" },
      { ...w(0.05), chemicalId: "myrcene" },
    ],
    notes: "Peel oil dominated by limonene.",
    sourceRefs: ["PubChem", "FlavorDB ingredient profiles"],
  },
  {
    id: "orange",
    name: "Orange",
    kind: "food",
    synonyms: ["orange peel", "sweet orange"],
    constituents: [
      { ...w(0.7), chemicalId: "limonene" },
      { ...w(0.1), chemicalId: "linalool" },
      { ...w(0.05), chemicalId: "alpha-pinene" },
    ],
    notes: "Peel oil dominated by limonene.",
    sourceRefs: ["FlavorDB ingredient profiles"],
  },
  {
    id: "strawberry",
    name: "Strawberry",
    kind: "food",
    synonyms: ["ripe strawberry", "strawberry aroma"],
    constituents: [
      { ...w(0.35), chemicalId: "methyl-butyrate" },
      { ...w(0.3), chemicalId: "ethyl-butyrate" },
      { ...w(0.15), chemicalId: "isoamyl-acetate" },
      { ...w(0.1), chemicalId: "hexanal" },
    ],
    notes: "Esters dominate fresh strawberry aroma.",
    sourceRefs: ["FlavorDB ingredient profiles"],
  },
  {
    id: "apple",
    name: "Apple",
    kind: "food",
    synonyms: ["fresh apple", "apple aroma", "granny smith"],
    constituents: [
      { ...w(0.3), chemicalId: "hexanal" },
      { ...w(0.25), chemicalId: "e2-hexenal" },
      { ...w(0.2), chemicalId: "butyl-acetate" },
      { ...w(0.1), chemicalId: "ethyl-butyrate" },
    ],
    notes: "Green aldehydes + fruity esters; ripening shifts toward esters.",
    sourceRefs: ["FlavorDB ingredient profiles"],
  },
  {
    id: "tomato",
    name: "Tomato",
    kind: "food",
    synonyms: ["fresh tomato", "tomato leaf", "ripe tomato"],
    constituents: [
      { ...w(0.4), chemicalId: "hexanal" },
      { ...w(0.3), chemicalId: "e2-hexenal" },
      { ...w(0.15), chemicalId: "hexanol" },
      { ...w(0.05), chemicalId: "limonene" },
    ],
    notes: "Green-leaf volatiles (C6 aldehydes) dominate.",
    sourceRefs: ["FlavorDB ingredient profiles"],
  },
  {
    id: "vinegar",
    name: "Vinegar",
    kind: "food",
    synonyms: ["white vinegar", "apple cider vinegar", "acetic acid vinegar"],
    constituents: [
      { ...w(0.85), chemicalId: "acetic-acid" },
      { ...w(0.05), chemicalId: "acetaldehyde" },
    ],
    notes: "Essentially an aqueous acetic acid solution.",
    sourceRefs: [],
  },
  {
    id: "wine",
    name: "Wine",
    kind: "beverage",
    synonyms: ["red wine", "white wine", "grape wine"],
    constituents: [
      { ...w(0.7), chemicalId: "ethanol" },
      { ...w(0.15), chemicalId: "ethyl-acetate" },
      { ...w(0.05), chemicalId: "ethyl-butyrate" },
      { ...w(0.05), chemicalId: "acetic-acid" },
    ],
    notes: "Ethanol-dominated with fruity fermentation esters.",
    sourceRefs: ["FlavorDB ingredient profiles"],
  },
  {
    id: "beer",
    name: "Beer",
    kind: "beverage",
    synonyms: ["lager", "ale", "draft beer"],
    constituents: [
      { ...w(0.55), chemicalId: "ethanol" },
      { ...w(0.1), chemicalId: "myrcene" },
      { ...w(0.1), chemicalId: "linalool" },
      { ...w(0.05), chemicalId: "diacetyl" },
      { ...w(0.05), chemicalId: "acetic-acid" },
    ],
    notes: "Ethanol plus hop and fermentation aromatics; diacetyl gives buttery off-note.",
    sourceRefs: ["FlavorDB ingredient profiles"],
  },
  {
    id: "bread",
    name: "Bread",
    kind: "food",
    synonyms: ["fresh bread", "baked bread", "bread crust"],
    constituents: [
      { ...w(0.3), chemicalId: "diacetyl" },
      { ...w(0.2), chemicalId: "furfural" },
      { ...w(0.15), chemicalId: "acetaldehyde" },
      { ...w(0.1), chemicalId: "ethanol" },
    ],
    notes: "Maillard/bakey aromatics; simplified subset.",
    sourceRefs: ["FlavorDB ingredient profiles"],
  },
  {
    id: "spoiled-milk",
    name: "Spoiled milk",
    kind: "food",
    synonyms: ["sour milk", "off milk", "spoiled dairy"],
    constituents: [
      { ...w(0.45), chemicalId: "butyric-acid" },
      { ...w(0.2), chemicalId: "dimethyl-sulfide" },
      { ...w(0.15), chemicalId: "hydrogen-sulfide" },
      { ...w(0.1), chemicalId: "acetaldehyde" },
    ],
    notes: "Lipolysis + protein degradation produce butyric acid and sulfides.",
    sourceRefs: ["Food spoilage literature (Dairy Science)"],
  },
  {
    id: "gasoline",
    name: "Gasoline",
    kind: "material",
    synonyms: ["petrol", "fuel", "unleaded gasoline"],
    constituents: [
      { ...w(0.35), chemicalId: "toluene" },
      { ...w(0.25), chemicalId: "xylene" },
      { ...w(0.15), chemicalId: "hexane" },
      { ...w(0.1), chemicalId: "benzene" },
      { ...w(0.1), chemicalId: "isopentane" },
    ],
    notes: "BTX + alkanes dominate light-fuel headspace; highly variable by blend.",
    sourceRefs: ["ASTM fuel composition data"],
  },
  {
    id: "wood-smoke",
    name: "Wood smoke",
    kind: "activity",
    synonyms: ["smoke", "fire smoke", "campfire", "burning wood"],
    constituents: [
      { ...w(0.35), chemicalId: "guaiacol" },
      { ...w(0.25), chemicalId: "phenol" },
      { ...w(0.1), chemicalId: "eugenol" },
      { ...w(0.1), chemicalId: "acetaldehyde" },
      { ...w(0.05), chemicalId: "furfural" },
    ],
    notes: "Phenolic signature of pyrolysis; simplified subset.",
    sourceRefs: ["Smoke chemistry literature"],
  },
  {
    id: "paint-thinner",
    name: "Paint thinner",
    kind: "product",
    synonyms: ["mineral spirits", "white spirit", "solvent"],
    constituents: [
      { ...w(0.4), chemicalId: "toluene" },
      { ...w(0.3), chemicalId: "xylene" },
      { ...w(0.15), chemicalId: "ethyl-acetate" },
      { ...w(0.1), chemicalId: "acetone" },
    ],
    notes: "Aromatic + ester solvents dominate.",
    sourceRefs: ["MSDS / solvent formulation data"],
  },
  {
    id: "nail-polish-remover",
    name: "Nail polish remover",
    kind: "product",
    synonyms: ["acetone remover", "polish remover"],
    constituents: [{ ...w(0.9), chemicalId: "acetone" }],
    notes: "Essentially acetone.",
    sourceRefs: [],
  },
  {
    id: "hand-sanitizer",
    name: "Hand sanitizer",
    kind: "product",
    synonyms: ["sanitizer gel", "hand rub", "alcohol gel"],
    constituents: [
      { ...w(0.7), chemicalId: "ethanol" },
      { ...w(0.2), chemicalId: "isopropanol" },
    ],
    notes: "Alcohol gel; residue is ethanol/IPA.",
    sourceRefs: ["CDC formulation guidance"],
  },
  {
    id: "natural-gas",
    name: "Natural gas",
    kind: "activity",
    synonyms: ["gas leak", "methane leak", "utility gas"],
    constituents: [
      { ...w(0.9), chemicalId: "methane" },
      { ...w(0.05), chemicalId: "methanethiol" },
      { ...w(0.05), chemicalId: "butane" },
    ],
    notes: "Methane plus added sulfur odorant (mercaptan).",
    sourceRefs: ["Gas utility odorization standards"],
  },
  {
    id: "propane-leak",
    name: "Propane / LPG",
    kind: "activity",
    synonyms: ["propane tank", "grill gas", "LPG leak"],
    constituents: [
      { ...w(0.95), chemicalId: "propane" },
      { ...w(0.05), chemicalId: "methanethiol" },
    ],
    notes: "Propane plus added sulfur odorant.",
    sourceRefs: ["LPG odorization standards"],
  },
  {
    id: "sewer",
    name: "Sewer odor",
    kind: "activity",
    synonyms: ["drain smell", "septic", "wastewater"],
    constituents: [
      { ...w(0.45), chemicalId: "hydrogen-sulfide" },
      { ...w(0.25), chemicalId: "ammonia" },
      { ...w(0.15), chemicalId: "methanethiol" },
      { ...w(0.1), chemicalId: "dimethyl-sulfide" },
    ],
    notes: "Hydrogen sulfide is the dominant signature.",
    sourceRefs: ["Wastewater odor literature"],
  },
  {
    id: "rotten-egg",
    name: "Rotten egg",
    kind: "food",
    synonyms: ["sulfurous egg", "bad egg"],
    constituents: [{ ...w(0.95), chemicalId: "hydrogen-sulfide" }],
    notes: "H2S from protein sulfur decomposition.",
    sourceRefs: [],
  },
  {
    id: "car-exhaust",
    name: "Car exhaust",
    kind: "activity",
    synonyms: ["vehicle exhaust", "tailpipe", "engine emissions"],
    constituents: [
      { ...w(0.8), chemicalId: "carbon-monoxide" },
      { ...w(0.05), chemicalId: "acetaldehyde" },
      { ...w(0.05), chemicalId: "benzene" },
    ],
    notes: "CO-dominated for gasoline cold-start; simplified subset.",
    sourceRefs: ["Combustion emission literature"],
  },
  {
    id: "ripe-fruit-gas",
    name: "Ripe fruit (ethylene)",
    kind: "activity",
    synonyms: ["ethylene ripening", "fruit ripening", "climacteric fruit gas"],
    constituents: [{ ...w(0.9), chemicalId: "ethylene" }],
    notes: "Ethylene is the climacteric ripening hormone emitted by ripening fruit.",
    sourceRefs: ["Plant physiology literature"],
  },
]

export const COMPOSITE_BY_ID: Map<string, Composite> = new Map(COMPOSITES.map((c) => [c.id, c]))
