import type { Composite } from "./types"

const w = (value: number, source: "measured" | "estimated" = "estimated") => ({
  weightFraction: { value, source },
  chemicalId: "",
})

export const COMPOSITES: Composite[] = [
  {
    id: "banana",
    name: "Banana",
    kind: "food",
    synonyms: ["ripe banana", "banana fruit", "banana aroma"],
    constituents: [
      { ...w(0.5), chemicalId: "isoamyl-acetate" },
      { ...w(0.15), chemicalId: "isoamyl-butyrate" },
      { ...w(0.1), chemicalId: "butyl-acetate" },
      { ...w(0.1), chemicalId: "isoamyl-isovalerate" },
      { ...w(0.05), chemicalId: "hexanal" },
      { ...w(0.05), chemicalId: "e2-hexenal" },
      { ...w(0.05), chemicalId: "hexanol" },
    ],
    notes:
      "Character impact is isoamyl acetate; esters dominate ripe-fruit headspace. Profile varies with ripeness (green stage is aldehyde-heavy).",
    sourceRefs: ["Zhu et al. 2018 (Molecules)", "Pino & Febles 2013", "Sutikdja et al. 2012"],
  },
  {
    id: "cinnamon",
    name: "Cinnamon",
    kind: "spice",
    synonyms: ["cinnamon bark", "cinnamon powder", "ceylon cinnamon"],
    constituents: [
      { ...w(0.65), chemicalId: "cinnamaldehyde" },
      { ...w(0.2), chemicalId: "eugenol" },
      { ...w(0.05), chemicalId: "linalool" },
      { ...w(0.05), chemicalId: "limonene" },
    ],
    notes: "Simplified profile dominated by cinnamaldehyde (bark).",
    sourceRefs: ["PubChem", "FlavorDB ingredient profiles"],
  },
  {
    id: "coffee",
    name: "Coffee",
    kind: "beverage",
    synonyms: ["roasted coffee", "coffee beans", "espresso"],
    constituents: [
      { ...w(0.25), chemicalId: "diacetyl" },
      { ...w(0.2), chemicalId: "furfural" },
      { ...w(0.15), chemicalId: "acetaldehyde" },
      { ...w(0.15), chemicalId: "acetic-acid" },
      { ...w(0.1), chemicalId: "guaiacol" },
    ],
    notes:
      "Highly complex headspace (200+ VOCs); this is a simplified representative subset of potent roast volatiles.",
    sourceRefs: ["FlavorDB2", "Chambers & Koppel 2013 (Molecules)"],
  },
  {
    id: "garlic",
    name: "Garlic",
    kind: "food",
    synonyms: ["raw garlic", "garlic clove", "garlic powder"],
    constituents: [
      { ...w(0.6), chemicalId: "diallyl-disulfide" },
      { ...w(0.15), chemicalId: "methanethiol" },
      { ...w(0.1), chemicalId: "dimethyl-sulfide" },
    ],
    notes: "Organosulfur compounds dominate and are potent MOX-reducing agents.",
    sourceRefs: ["FlavorDB ingredient profiles", "Lanzotti 2006"],
  },
  {
    id: "peppermint",
    name: "Peppermint",
    kind: "spice",
    synonyms: ["mint", "peppermint oil", "mint oil"],
    constituents: [
      { ...w(0.55), chemicalId: "menthol" },
      { ...w(0.3), chemicalId: "menthone" },
      { ...w(0.15), chemicalId: "limonene" },
    ],
    notes: "Menthol + menthone dominate; limonene adds citrus lift.",
    sourceRefs: ["FlavorDB ingredient profiles"],
  },
  {
    id: "lemon",
    name: "Lemon",
    kind: "food",
    synonyms: ["lemon peel", "lemon zest", "citrus lemon"],
    constituents: [
      { ...w(0.6), chemicalId: "limonene" },
      { ...w(0.15), chemicalId: "linalool" },
      { ...w(0.1), chemicalId: "alpha-pinene" },
      { ...w(0.05), chemicalId: "myrcene" },
    ],
    notes: "Peel oil dominated by limonene.",
    sourceRefs: ["PubChem", "FlavorDB ingredient profiles"],
  },
  {
    id: "orange",
    name: "Orange",
    kind: "food",
    synonyms: ["orange peel", "sweet orange"],
    constituents: [
      { ...w(0.7), chemicalId: "limonene" },
      { ...w(0.1), chemicalId: "linalool" },
      { ...w(0.05), chemicalId: "alpha-pinene" },
    ],
    notes: "Peel oil dominated by limonene.",
    sourceRefs: ["FlavorDB ingredient profiles"],
  },
  {
    id: "strawberry",
    name: "Strawberry",
    kind: "food",
    synonyms: ["ripe strawberry", "strawberry aroma"],
    constituents: [
      { ...w(0.35), chemicalId: "methyl-butyrate" },
      { ...w(0.3), chemicalId: "ethyl-butyrate" },
      { ...w(0.15), chemicalId: "isoamyl-acetate" },
      { ...w(0.1), chemicalId: "hexanal" },
    ],
    notes: "Esters dominate fresh strawberry aroma.",
    sourceRefs: ["FlavorDB ingredient profiles"],
  },
  {
    id: "apple",
    name: "Apple",
    kind: "food",
    synonyms: ["fresh apple", "apple aroma", "granny smith"],
    constituents: [
      { ...w(0.3), chemicalId: "hexanal" },
      { ...w(0.25), chemicalId: "e2-hexenal" },
      { ...w(0.2), chemicalId: "butyl-acetate" },
      { ...w(0.1), chemicalId: "ethyl-butyrate" },
    ],
    notes: "Green aldehydes + fruity esters; ripening shifts toward esters.",
    sourceRefs: ["FlavorDB ingredient profiles"],
  },
  {
    id: "tomato",
    name: "Tomato",
    kind: "food",
    synonyms: ["fresh tomato", "tomato leaf", "ripe tomato"],
    constituents: [
      { ...w(0.4), chemicalId: "hexanal" },
      { ...w(0.3), chemicalId: "e2-hexenal" },
      { ...w(0.15), chemicalId: "hexanol" },
      { ...w(0.05), chemicalId: "limonene" },
    ],
    notes: "Green-leaf volatiles (C6 aldehydes) dominate.",
    sourceRefs: ["FlavorDB ingredient profiles"],
  },
  {
    id: "vinegar",
    name: "Vinegar",
    kind: "food",
    synonyms: ["white vinegar", "apple cider vinegar", "acetic acid vinegar"],
    constituents: [
      { ...w(0.85), chemicalId: "acetic-acid" },
      { ...w(0.05), chemicalId: "acetaldehyde" },
    ],
    notes: "Essentially an aqueous acetic acid solution.",
    sourceRefs: [],
  },
  {
    id: "wine",
    name: "Wine",
    kind: "beverage",
    synonyms: ["red wine", "white wine", "grape wine"],
    constituents: [
      { ...w(0.7), chemicalId: "ethanol" },
      { ...w(0.15), chemicalId: "ethyl-acetate" },
      { ...w(0.05), chemicalId: "ethyl-butyrate" },
      { ...w(0.05), chemicalId: "acetic-acid" },
    ],
    notes: "Ethanol-dominated with fruity fermentation esters.",
    sourceRefs: ["FlavorDB ingredient profiles"],
  },
  {
    id: "beer",
    name: "Beer",
    kind: "beverage",
    synonyms: ["lager", "ale", "draft beer"],
    constituents: [
      { ...w(0.55), chemicalId: "ethanol" },
      { ...w(0.1), chemicalId: "myrcene" },
      { ...w(0.1), chemicalId: "linalool" },
      { ...w(0.05), chemicalId: "diacetyl" },
      { ...w(0.05), chemicalId: "acetic-acid" },
    ],
    notes: "Ethanol plus hop and fermentation aromatics; diacetyl gives buttery off-note.",
    sourceRefs: ["FlavorDB ingredient profiles"],
  },
  {
    id: "bread",
    name: "Bread",
    kind: "food",
    synonyms: ["fresh bread", "baked bread", "bread crust"],
    constituents: [
      { ...w(0.3), chemicalId: "diacetyl" },
      { ...w(0.2), chemicalId: "furfural" },
      { ...w(0.15), chemicalId: "acetaldehyde" },
      { ...w(0.1), chemicalId: "ethanol" },
    ],
    notes: "Maillard/bakey aromatics; simplified subset.",
    sourceRefs: ["FlavorDB ingredient profiles"],
  },
  {
    id: "spoiled-milk",
    name: "Spoiled milk",
    kind: "food",
    synonyms: ["sour milk", "off milk", "spoiled dairy"],
    constituents: [
      { ...w(0.45), chemicalId: "butyric-acid" },
      { ...w(0.2), chemicalId: "dimethyl-sulfide" },
      { ...w(0.15), chemicalId: "hydrogen-sulfide" },
      { ...w(0.1), chemicalId: "acetaldehyde" },
    ],
    notes: "Lipolysis + protein degradation produce butyric acid and sulfides.",
    sourceRefs: ["Food spoilage literature (Dairy Science)"],
  },
  {
    id: "gasoline",
    name: "Gasoline",
    kind: "material",
    synonyms: ["petrol", "fuel", "unleaded gasoline"],
    constituents: [
      { ...w(0.35), chemicalId: "toluene" },
      { ...w(0.25), chemicalId: "xylene" },
      { ...w(0.15), chemicalId: "hexane" },
      { ...w(0.1), chemicalId: "benzene" },
      { ...w(0.1), chemicalId: "isopentane" },
    ],
    notes: "BTX + alkanes dominate light-fuel headspace; highly variable by blend.",
    sourceRefs: ["ASTM fuel composition data"],
  },
  {
    id: "wood-smoke",
    name: "Wood smoke",
    kind: "activity",
    synonyms: ["smoke", "fire smoke", "campfire", "burning wood"],
    constituents: [
      { ...w(0.35), chemicalId: "guaiacol" },
      { ...w(0.25), chemicalId: "phenol" },
      { ...w(0.1), chemicalId: "eugenol" },
      { ...w(0.1), chemicalId: "acetaldehyde" },
      { ...w(0.05), chemicalId: "furfural" },
    ],
    notes: "Phenolic signature of pyrolysis; simplified subset.",
    sourceRefs: ["Smoke chemistry literature"],
  },
  {
    id: "paint-thinner",
    name: "Paint thinner",
    kind: "product",
    synonyms: ["mineral spirits", "white spirit", "solvent"],
    constituents: [
      { ...w(0.4), chemicalId: "toluene" },
      { ...w(0.3), chemicalId: "xylene" },
      { ...w(0.15), chemicalId: "ethyl-acetate" },
      { ...w(0.1), chemicalId: "acetone" },
    ],
    notes: "Aromatic + ester solvents dominate.",
    sourceRefs: ["MSDS / solvent formulation data"],
  },
  {
    id: "nail-polish-remover",
    name: "Nail polish remover",
    kind: "product",
    synonyms: ["acetone remover", "polish remover"],
    constituents: [{ ...w(0.9), chemicalId: "acetone" }],
    notes: "Essentially acetone.",
    sourceRefs: [],
  },
  {
    id: "hand-sanitizer",
    name: "Hand sanitizer",
    kind: "product",
    synonyms: ["sanitizer gel", "hand rub", "alcohol gel"],
    constituents: [
      { ...w(0.7), chemicalId: "ethanol" },
      { ...w(0.2), chemicalId: "isopropanol" },
    ],
    notes: "Alcohol gel; residue is ethanol/IPA.",
    sourceRefs: ["CDC formulation guidance"],
  },
  {
    id: "natural-gas",
    name: "Natural gas",
    kind: "activity",
    synonyms: ["gas leak", "methane leak", "utility gas"],
    constituents: [
      { ...w(0.9), chemicalId: "methane" },
      { ...w(0.05), chemicalId: "methanethiol" },
      { ...w(0.05), chemicalId: "butane" },
    ],
    notes: "Methane plus added sulfur odorant (mercaptan).",
    sourceRefs: ["Gas utility odorization standards"],
  },
  {
    id: "propane-leak",
    name: "Propane / LPG",
    kind: "activity",
    synonyms: ["propane tank", "grill gas", "LPG leak"],
    constituents: [
      { ...w(0.95), chemicalId: "propane" },
      { ...w(0.05), chemicalId: "methanethiol" },
    ],
    notes: "Propane plus added sulfur odorant.",
    sourceRefs: ["LPG odorization standards"],
  },
  {
    id: "sewer",
    name: "Sewer odor",
    kind: "activity",
    synonyms: ["drain smell", "septic", "wastewater"],
    constituents: [
      { ...w(0.45), chemicalId: "hydrogen-sulfide" },
      { ...w(0.25), chemicalId: "ammonia" },
      { ...w(0.15), chemicalId: "methanethiol" },
      { ...w(0.1), chemicalId: "dimethyl-sulfide" },
    ],
    notes: "Hydrogen sulfide is the dominant signature.",
    sourceRefs: ["Wastewater odor literature"],
  },
  {
    id: "rotten-egg",
    name: "Rotten egg",
    kind: "food",
    synonyms: ["sulfurous egg", "bad egg"],
    constituents: [{ ...w(0.95), chemicalId: "hydrogen-sulfide" }],
    notes: "H2S from protein sulfur decomposition.",
    sourceRefs: [],
  },
  {
    id: "car-exhaust",
    name: "Car exhaust",
    kind: "activity",
    synonyms: ["vehicle exhaust", "tailpipe", "engine emissions"],
    constituents: [
      { ...w(0.8), chemicalId: "carbon-monoxide" },
      { ...w(0.05), chemicalId: "acetaldehyde" },
      { ...w(0.05), chemicalId: "benzene" },
    ],
    notes: "CO-dominated for gasoline cold-start; simplified subset.",
    sourceRefs: ["Combustion emission literature"],
  },
  {
    id: "ripe-fruit-gas",
    name: "Ripe fruit (ethylene)",
    kind: "activity",
    synonyms: ["ethylene ripening", "fruit ripening", "climacteric fruit gas"],
    constituents: [{ ...w(0.9), chemicalId: "ethylene" }],
    notes: "Ethylene is the climacteric ripening hormone emitted by ripening fruit.",
    sourceRefs: ["Plant physiology literature"],
  },
  {
    id: "lavender",
    name: "Lavender",
    kind: "spice",
    synonyms: ["lavender oil", "lavender flower", "lavender essential oil"],
    constituents: [
      { ...w(0.5), chemicalId: "linalool" },
      { ...w(0.4), chemicalId: "gen-8294" },
      { ...w(0.1), chemicalId: "gen-17100" },
    ],
    notes: "Linalool + linalyl acetate dominate true lavender oil; camphor-heavy lavandin is a distinct cultivar.",
    sourceRefs: ["FlavorDB ingredient profiles", "Lavender oil GC-MS literature"],
  },
  {
    id: "eucalyptus",
    name: "Eucalyptus",
    kind: "spice",
    synonyms: ["eucalyptus oil", "eucalyptus leaves", "eucalyptus scent"],
    constituents: [
      { ...w(0.7), chemicalId: "gen-2758" },
      { ...w(0.15), chemicalId: "alpha-pinene" },
      { ...w(0.1), chemicalId: "gen-7463" },
      { ...w(0.05), chemicalId: "gen-17100" },
    ],
    notes: "1,8-cineole (eucalyptol) is the dominant signature, giving the characteristic camphoraceous-eucalyptus note.",
    sourceRefs: ["Eucalyptus oil GC-MS literature", "PubChem"],
  },
  {
    id: "citronella",
    name: "Citronella",
    kind: "product",
    synonyms: ["citronella oil", "citronella candle", "mosquito repellent", "citronella scent"],
    constituents: [
      { ...w(0.4), chemicalId: "gen-7794" },
      { ...w(0.3), chemicalId: "gen-637566" },
      { ...w(0.2), chemicalId: "gen-8842" },
      { ...w(0.1), chemicalId: "limonene" },
    ],
    notes: "Citronellal + geraniol/citronellol dominate citronella oil — the classic candle-and-torch repellent profile.",
    sourceRefs: ["Citronella oil GC-MS literature"],
  },
  {
    id: "skunk",
    name: "Skunk odor",
    kind: "activity",
    synonyms: ["skunk spray", "skunk smell", "skunk musk"],
    constituents: [
      { ...w(0.6), chemicalId: "gen-8012" },
      { ...w(0.25), chemicalId: "gen-6343" },
      { ...w(0.15), chemicalId: "gen-6387" },
    ],
    notes: "Low-molecular-weight thiols (butanethiol, ethanethiol) are among the most potent MOX-reducing odorants.",
    sourceRefs: ["Skunk spray chemistry literature"],
  },
  {
    id: "fresh-cut-grass",
    name: "Fresh cut grass",
    kind: "activity",
    synonyms: ["cut grass", "mowed lawn", "newly mown grass", "grass smell"],
    constituents: [
      { ...w(0.5), chemicalId: "gen-5281167" },
      { ...w(0.25), chemicalId: "hexanal" },
      { ...w(0.25), chemicalId: "e2-hexenal" },
    ],
    notes: "Leaf alcohol ((Z)-3-hexen-1-ol) and C6 aldehydes are the classic green-leaf volatiles released on wounding.",
    sourceRefs: ["Green leaf volatile literature (Hatanaka 1993)"],
  },
  {
    id: "vanilla",
    name: "Vanilla",
    kind: "food",
    synonyms: ["vanilla extract", "vanilla bean", "vanilla aroma", "vanillin"],
    constituents: [
      { ...w(0.85), chemicalId: "gen-1183" },
      { ...w(0.15), chemicalId: "gen-8467" },
    ],
    notes: "Vanillin dominates; ethyl vanillin (synthetic, ~3× sweeter) is the common extract additive.",
    sourceRefs: ["PubChem", "Vanilla flavor chemistry literature"],
  },
  {
    id: "rose",
    name: "Rose",
    kind: "spice",
    synonyms: ["rose oil", "rose petals", "rose scent", "rose flower"],
    constituents: [
      { ...w(0.5), chemicalId: "gen-6054" },
      { ...w(0.3), chemicalId: "gen-637566" },
      { ...w(0.2), chemicalId: "gen-8842" },
    ],
    notes: "Phenylethyl alcohol gives the characteristic rose note, with geraniol and citronellol rounding it out.",
    sourceRefs: ["Rose oil GC-MS literature", "PubChem"],
  },
  {
    id: "onion",
    name: "Onion",
    kind: "food",
    synonyms: ["fresh onion", "onion odor", "cut onion", "raw onion", "onion powder"],
    constituents: [
      { ...w(0.5), chemicalId: "gen-12377" },
      { ...w(0.2), chemicalId: "methanethiol" },
      { ...w(0.2), chemicalId: "dimethyl-sulfide" },
      { ...w(0.1), chemicalId: "diallyl-disulfide" },
    ],
    notes: "Dipropyl disulfide and volatile sulfides dominate fresh-cut onion; lachrymatory chemistry converts to thiols quickly.",
    sourceRefs: ["Allium volatile literature (Lanzotti 2006)"],
  },
  {
    id: "pine-forest",
    name: "Pine forest",
    kind: "activity",
    synonyms: ["pine", "pine needles", "christmas tree", "conifer", "forest air", "pine trees"],
    constituents: [
      { ...w(0.4), chemicalId: "alpha-pinene" },
      { ...w(0.25), chemicalId: "gen-14896" },
      { ...w(0.15), chemicalId: "gen-6616" },
      { ...w(0.1), chemicalId: "myrcene" },
      { ...w(0.1), chemicalId: "limonene" },
    ],
    notes: "Pinenes dominate conifer resin headspace; camphene and myrcene add the terpene lift.",
    sourceRefs: ["Conifer volatile literature"],
  },
  {
    id: "fish",
    name: "Fish / seafood",
    kind: "food",
    synonyms: ["fishy", "fresh fish", "seafood", "raw fish", "fish odor"],
    constituents: [
      { ...w(0.7), chemicalId: "gen-1146" },
      { ...w(0.15), chemicalId: "dimethyl-sulfide" },
      { ...w(0.15), chemicalId: "hexanal" },
    ],
    notes: "Trimethylamine is the signature 'fishy' amine; spoilage shifts the balance toward sulfides and aldehydes.",
    sourceRefs: ["Seafood freshness literature"],
  },
  {
    id: "mothballs",
    name: "Mothballs",
    kind: "product",
    synonyms: ["moth ball", "moth repellent", "naphthalene balls", "mothball smell"],
    constituents: [
      { ...w(0.6), chemicalId: "gen-931" },
      { ...w(0.4), chemicalId: "gen-4685" },
    ],
    notes: "Naphthalene or p-dichlorobenzene (1,4-dichlorobenzene) — strong, persistent aromatic sublimation odor.",
    sourceRefs: ["Consumer product composition data"],
  },
  {
    id: "clove",
    name: "Clove",
    kind: "spice",
    synonyms: ["cloves", "clove oil", "whole cloves", "clove bud"],
    constituents: [
      { ...w(0.7), chemicalId: "eugenol" },
      { ...w(0.15), chemicalId: "gen-853433" },
      { ...w(0.15), chemicalId: "gen-5281515" },
    ],
    notes: "Eugenol is the dominant clove character; isoeugenol and caryophyllene round out the bud.",
    sourceRefs: ["Clove oil GC-MS literature"],
  },
  {
    id: "spearmint",
    name: "Spearmint",
    kind: "spice",
    synonyms: ["spearmint gum", "spearmint oil", "spearmint leaves"],
    constituents: [
      { ...w(0.6), chemicalId: "gen-7439" },
      { ...w(0.25), chemicalId: "limonene" },
      { ...w(0.15), chemicalId: "linalool" },
    ],
    notes: "Carvone is the distinct spearmint signature — the same molecule family that separates it from peppermint's menthol.",
    sourceRefs: ["Mint essential oil literature"],
  },
  {
    id: "thyme",
    name: "Thyme",
    kind: "spice",
    synonyms: ["thyme herb", "fresh thyme", "thyme leaves", "dried thyme"],
    constituents: [
      { ...w(0.5), chemicalId: "gen-6989" },
      { ...w(0.2), chemicalId: "gen-7463" },
      { ...w(0.15), chemicalId: "linalool" },
      { ...w(0.15), chemicalId: "alpha-pinene" },
    ],
    notes: "Thymol gives the thyme character; p-cymene and linalool contribute the herbal lift.",
    sourceRefs: ["Thyme oil GC-MS literature"],
  },
  {
    id: "rosemary",
    name: "Rosemary",
    kind: "spice",
    synonyms: ["rosemary herb", "fresh rosemary", "rosemary sprig", "rosemary oil"],
    constituents: [
      { ...w(0.4), chemicalId: "gen-2758" },
      { ...w(0.25), chemicalId: "alpha-pinene" },
      { ...w(0.2), chemicalId: "gen-2537" },
      { ...w(0.15), chemicalId: "linalool" },
    ],
    notes: "Eucalyptol + pinenes + camphor give rosemary its sharp, camphoraceous-woody profile.",
    sourceRefs: ["Rosemary oil GC-MS literature"],
  },
  {
    id: "black-tea",
    name: "Black tea",
    kind: "beverage",
    synonyms: ["tea", "brewed tea", "tea leaves", "hot tea", "tea aroma"],
    constituents: [
      { ...w(0.3), chemicalId: "linalool" },
      { ...w(0.2), chemicalId: "hexanal" },
      { ...w(0.2), chemicalId: "gen-637566" },
      { ...w(0.15), chemicalId: "gen-4133" },
      { ...w(0.15), chemicalId: "gen-6054" },
    ],
    notes: "Linalool, geraniol, and methyl salicylate dominate black-tea aroma; simplified representative subset.",
    sourceRefs: ["Tea aroma literature"],
  },
  {
    id: "chocolate",
    name: "Chocolate",
    kind: "food",
    synonyms: ["cocoa", "hot chocolate", "dark chocolate", "chocolate bar", "cocoa powder"],
    constituents: [
      { ...w(0.3), chemicalId: "diacetyl" },
      { ...w(0.25), chemicalId: "furfural" },
      { ...w(0.25), chemicalId: "gen-26808" },
      { ...w(0.2), chemicalId: "gen-1183" },
    ],
    notes: "Roast pyrazines, diacetyl, and vanillin build the cocoa character; simplified representative subset.",
    sourceRefs: ["Cocoa aroma literature (Chambers & Koppel 2013)"],
  },
  {
    id: "coconut",
    name: "Coconut",
    kind: "food",
    synonyms: ["coconut milk", "coconut oil", "fresh coconut", "coconut meat", "shredded coconut"],
    constituents: [
      { ...w(0.5), chemicalId: "gen-12810" },
      { ...w(0.3), chemicalId: "gen-7710" },
      { ...w(0.2), chemicalId: "gen-12813" },
    ],
    notes: "Lactones (δ-decalactone, γ-nonalactone) give coconut its creamy-sweet signature.",
    sourceRefs: ["Coconut flavor literature"],
  },
  {
    id: "peach",
    name: "Peach",
    kind: "food",
    synonyms: ["ripe peach", "peach aroma", "peach fruit", "fresh peach"],
    constituents: [
      { ...w(0.5), chemicalId: "gen-12813" },
      { ...w(0.2), chemicalId: "gen-7714" },
      { ...w(0.15), chemicalId: "gen-7710" },
      { ...w(0.15), chemicalId: "hexanal" },
    ],
    notes: "C10–C11 lactones carry the peach lactonic note, backed by green aldehydes.",
    sourceRefs: ["Peach aroma literature"],
  },
  {
    id: "violet",
    name: "Violet",
    kind: "other",
    synonyms: ["violet flower", "violet scent", "violets"],
    constituents: [
      { ...w(0.7), chemicalId: "gen-5282108" },
      { ...w(0.3), chemicalId: "gen-638014" },
    ],
    notes: "The α- and β-ionones are the classic violet/iris perfumery note.",
    sourceRefs: ["Perfumery chemistry literature", "PubChem"],
  },
]

export const COMPOSITE_BY_ID: Map<string, Composite> = new Map(COMPOSITES.map((c) => [c.id, c]))
