import { describe, expect, it } from "vitest"
import { searchSubstances } from "../search"

// Curated everyday-phrase → top-1 target mappings. Guards against a synonym or
// scoring change silently repointing a common phrase to the wrong profile.

const MAPS: [string, string][] = [
  ["banana", "banana"],
  ["cinnamon", "cinnamon"],
  ["coffee", "coffee"],
  ["garlic", "garlic"],
  ["gasoline", "gasoline"],
  ["spoiled milk", "spoiled-milk"],
  ["hand sanitizer", "hand-sanitizer"],
  ["rotten egg", "rotten-egg"],
  ["fresh cut grass", "fresh-cut-grass"],
  ["skunk", "skunk"],
  ["lavender", "lavender"],
  ["vanilla", "vanilla"],
  ["chocolate", "chocolate"],
  ["peanut butter", "peanut-butter"],
  ["maple syrup", "maple-syrup"],
  ["smoked fish", "fish"],
  ["marijuana smoke", "cannabis"],
  ["chili pepper", "chili-pepper"],
  ["jalapeño", "chili-pepper"],
  ["sesame oil", "sesame"],
  ["tahini", "sesame"],
  ["curry", "curry"],
  ["sriracha", "chili-pepper"],
  ["worcestershire", "miso"],
  ["sauerkraut", "miso"],
  ["fish sauce", "miso"],
  ["mothballs", "mothballs"],
  ["burnt toast", "burnt-toast"],
  ["wet dog", "wet-dog"],
  ["campfire", "wood-smoke"],
  ["chicken coop", "barnyard"],
  ["dog breath", "dog-breath"],
  ["rotten meat", "rotten-meat"],
  ["ranch dressing", "salad-dressing"],
  ["canola oil", "cooking-oil"],
  ["olive oil", "cooking-oil"],
  ["scallop", "seafood"],
  ["eel", "seafood"],
  ["jerky", "cured-meat"],
  ["salami", "cured-meat"],
  ["hot dog", "cured-meat"],
  ["lettuce", "salad-greens"],
  ["raisin", "dried-fruit"],
  ["nectarine", "peach"],
  ["pear", "pear"],
  ["soy milk", "soy-milk"],
  ["candy apple", "apple"],
  ["playdough", "playdough"],
  ["adhesive tape", "glue"],
  ["perfume", "perfume"],
  ["tear gas", "tear-gas"],
  ["pepper spray", "chili-pepper"],
  ["tabasco", "chili-pepper"],
  ["sauna", "sauna"],
  ["vinyl", "vinyl"],
  ["sheep", "barnyard"],
  ["expired milk", "spoiled-milk"],
  ["buttermilk", "yogurt"],
  ["turkey", "cooked-chicken"],
  ["pork", "cooked-beef"],
  ["duck", "cooked-chicken"],
  ["curing", "cured-meat"],
  ["brown sugar", "molasses"],
  ["fruit punch", "orange-juice"],
  ["green pepper", "capsicum"],
  ["habanero", "chili-pepper"],
  ["chervil", "parsley"],
  ["za'atar", "thyme"],
  ["galangal", "thai-aromatic"],
  ["shiso", "peppermint"],
  ["hummus", "hummus"],
  ["falafel", "hummus"],
  ["kimchi", "miso"],
  ["tulip", "spring-flowers"],
  ["amber", "amber"],
  ["cured meat", "cured-meat"],
  ["vinyl flooring", "vinyl"],
  ["chili oil", "chili-pepper"],
  ["five spice", "curry"],
  ["garlic powder", "garlic"],
  ["brewing", "beer"],
  ["electrical fire", "electrical-fire"],
  ["bleach and ammonia", "bleach-ammonia"],
  ["bleach and vinegar", "bleach-acid"],
  ["hydrogen peroxide and vinegar", "peroxide-vinegar"],
  ["vinegar and baking soda", "vinegar-baking-soda"],
  ["lemon juice and baking soda", "lemon-baking-soda"],
  ["ginger", "ginger"],
  ["ginger root", "ginger"],
  ["fresh ginger", "ginger"],
  ["cumin", "cumin"],
  ["jeera", "cumin"],
]

describe("everyday top-1 mappings", () => {
  it.each(MAPS)("%s resolves to %s", (q, want) => {
    const r = searchSubstances(q, 1)
    expect(r[0]?.id, q).toBe(want)
  })
})
